Try to make installer work
FossilOrigin-Name: ce07ff5188d8c6174ca0c4a9bc996be593de63d7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6993,6 +6993,32 @@ echo "$as_me: error: could not find tcl source file '${srcdir}/$i'" >&2;}
 
 
 
+    vars="library/datalog.tcl library/coroutine_corovar.tcl"
+    for i in $vars; do
+	# check for existence, be strict because it is installed
+	if test ! -f "${srcdir}/$i" ; then
+	    { { echo "$as_me:$LINENO: error: could not find tcl source file '${srcdir}/$i'" >&5
+echo "$as_me: error: could not find tcl source file '${srcdir}/$i'" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	PKG_TCL_SOURCES="$PKG_TCL_SOURCES $i"
+    done
+
+
+
+    vars="library/coroutine_iterator.tcl"
+    for i in $vars; do
+	# check for existence, be strict because it is installed
+	if test ! -f "${srcdir}/$i" ; then
+	    { { echo "$as_me:$LINENO: error: could not find tcl source file '${srcdir}/$i'" >&5
+echo "$as_me: error: could not find tcl source file '${srcdir}/$i'" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	PKG_TCL_SOURCES="$PKG_TCL_SOURCES $i"
+    done
+
+
+
 #--------------------------------------------------------------------
 #
 # You can add more files to clean if your extension creates any extra
